name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Configure git
      run: |
        git config --global user.email "runner@git-action.com"
        git config --global user.name "Github Action"

    - name: Clone v2fly/domain-list-community
      run: |
        git clone https://github.com/v2fly/domain-list-community.git
        mv domain-list-community/data data/

    - name: Genrate yaml files
      run: |
        python main.py

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'data'
        author_name: Github Action
        author_email: auto@github.com
        message: 'Update domain-yaml-community'
