name: Python Package using Conda

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Clone v2fly/domain-list-community
      run: |
        git clone https://github.com/v2fly/domain-list-community.git
        mv domain-list-community/data data/

    - name: Genrate yaml files
      run: |
        python main.py

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'yaml'
        author_name: Edward Chen
        author_email: hi@edch.top
        message: 'Update domain-yaml-community'
